---

- name: Get Docker hub auth
  uri:
    url: https://hub.docker.com/v2/users/login/
    body: '{"username": "{{docker_user}}", "password": "{{docker_password}}"}'
    body_format: json
  register: docker_login
  tags:
    - prepare_image
    - pull_only

- name: Get TripleO images list
  uri:
    url: "https://hub.docker.com/v2/repositories/{{ tripleo_image_repo }}/?page_size=200&q={{ tripleo_image_repo }}%2Fcentos-binary-"
    headers: "Authorization: JWT {{docker_login.cookies.token}}"
  register: images_list
  tags:
    - prepare_image
    - pull_only

- name: Pull TripleO image
  docker_image:
    name: "{{ tripleo_image_repo }}/{{ item.name }}"
    pull: yes
  with_items: "{{ images_list.json.results }}"
  tags: 
    - prepare_image
    - pull_only

- name: Save TreipleO image to tar
  shell: |
    docker image save {{ item.name }} -o {{ tripleo_image_tar_dest }}/{{ item.name }}.tar
  with_items: "{{ images_list.json.results }}"
  tags: 
    - prepare_image
    - tar_image
