---

- name: Install docker registry
  yum:
    name: docker-distribution
  tags: prepare

- name: Config registry
  template:
    src: ../templates/config.yaml.j2
    dest: /etc/docker-distribution/registry/config.yml
    mode: 0644
    owner: root
    group: root
  tags: prepare

- name: Config firewall accept registry port
  iptables:
    chain: INPUT
    destination_port: "{{ registry_port }}"
    protocol: tcp
    jump: ACCEPT
  become: yes
  tags: prepare

- name: Add insecure-registries json
  template:
    src: ../templates/daemon.json.j2
    dest: /etc/docker/daemon.json
    owner: root
    group: root
  tags: prepare

- name: Restart docker
  systemd:
    state: restarted
    name: docker

- name: Start docker-distribution
  systemd:
    name: docker-distribution
    state: started
    enabled: true
  tags: prepare
