---

- name: Get images name list
  shell: |
    # repository tag
    docker images | grep -v ID | awk '{print $1,$2}'
  register: docker_images

- name: Push all images
  shell: |
    docker tag {{ item.split(' ')[0] }}:{{ item.split(' ')[1] }} {{ registry_server }}:{{ registry_port }}/{{ item.split(' ')[0] }}:{{ item.split(' ')[1] }}
    docker push {{ registry_server }}:{{ registry_port }}/{{ item.split(' ')[0] }}:{{ item.split(' ')[1] }}
  with_items: "{{ docker_images.stdout_lines }}"
