---

- name: Install docker registry
  yum:
    name: docker-distribution

- name: Config registry
  template:
    src: ../templates/config.yaml.j2
    dest: /etc/docker-distribution/registry/config.yml
    mode: 0644
    owner: root
    group: root

- name: Config firewall accept registry port
  iptables:
    chain: INPUT
    destination_port: "{{ registry_port }}"
    protocol: tcp
    ctstate: NEW
    jump: ACCEPT
    action: insert
  become: yes

- name: Add insecure-registries json
  template:
    src: ../templates/daemon.json.j2
    dest: /etc/docker/daemon.json
    owner: root
    group: root
  register: this

- name: Restart docker
  systemd:
    state: restarted
    name: docker
  when: this.changed

- name: Start docker-distribution
  systemd:
    name: docker-distribution
    state: restarted
    enabled: true
