---
# This playbook will handle those tasks:
#   - install require pkgs
#   - create local registry
#   - prepare local registry images tarball for offline

# install requirement
- hosts: localhost
  gather_facts: no
  roles:
    - role: create-local-registry
      vars:
        - prepare: true
  tasks:
    - name: install jq
      yum:
        name:
          - files/jq/oniguruma-5.9.5-3.el7.x86_64.rpm
          - files/jq/jq-1.5-1.el7.x86_64.rpm
    - name: install docker-py
      pip:
        name: docker-py

# pull, push and create local registry
- hosts: localhost
  gather_facts: no
  become: true
  roles:
    - role: prepare-images
    - role: create-local-registry
      vars:
        create_by_tar: false

- hosts: localhost
  gather_facts: no
  tasks:
    - name: Tar all registry images
      archive:
        format: tar
        path: /var/lib/registry/docker
        dest: tripleo-images.tar
      when:
        - archive_images is defined
        - archive_images == true
