---
- hosts: localhost
  gather_facts: no
  tasks:
    - set_fact:
        default_image: /home/stack/tripleo-default-container-image.yaml
        tripleo_version: rocky
        offline_yum_registry: false
        local_registry: true

    - name: Install requirement
      include_role:
        name: undercloud

    - name: Prepare container image default env
      shell: |
        openstack tripleo container image prepare default --local-push-destination --output-env-file {{ default_image }}

    - tempfile:
        state: directory
      register: tmpdir

    - name: Prepare prototype undercloud.conf
      include_role:
        name: undercloud
        tasks_from: create-undercloud-conf.yaml

    - name: Merge undercloud config with custom config
      merge_configs:
        dest: /home/stack/undercloud.conf
        sources:
          - "../undercloud.conf"
          - "{{ tmpdir.path }}/undercloud.conf"
        owner: stack
        group: stack
        mode: 0644
