---
- hosts: localhost
  gather_facts: no
  tasks:
    - set_fact:
        default_image: /home/stack/tripleo-default-container-image.yaml
        tripleo_version: rocky
        offline_yum_registry: false

    - name: Install requirement
      include_role: undercloud

    - name: Prepare container image default env
      shell: |
        openstack tripleo container image prepare default --output-env-file {{ default_image }}

    - tempfile:
        state: directory
      register: tmpdir

    - name: Prepare prototype undercloud.conf
      include_role:
        name: undercloud
        tasks_from: create-undercloud-conf.yaml

    - name: Merge undercloud config with custom config
      merge_config:
        dest: /home/stack/undercloud.conf
        sources:
          - "../undercloud.conf"
          - "{{ tmpdir.path }}/undercloud.conf"
        owner: stack
        group: stack
        mode: 0644

    - name: Install Undercloud
      shell: |
        openstack undercloud install
      become: yes
      become_user: stack
      register: uc_install
      ignore_errors: yes

    - fail:
        msg: "Deploy undercloud with reistry fail please check /home/stack/install-undercloud.log"
      when: "uc_install.failed"

    - name: Create Overcloud required env
      shell: |
        openstack overcloud container image prepare --push-destination {{ registry_server }}:{{ registry_port }} --output-env-file /home/stack/overcloud-container-images.yaml

    - shell: |
        tail -n 22 /home/stack/install-undercloud.log
      register: ucmsg

    - debug:
        msg: |
         {{ ucmsg.stdout }}
         Overcloud image environment is at /home/stack/overcloud-container-images.yaml


