---
- name: Create stack group
  group:
    name: stack
    state: present

- name: Create stack user
  user:
    name: stack
    group: stack
    state: present
    shell: /bin/bash
    password: "{{ stack_user_password | default('password') | password_hash('sha512', 'mysecretsalt') }}"
    update_password: on_create

- name: Grant sudo privileges to stack user
  copy:
    content: |
      stack ALL=(ALL) NOPASSWD:ALL
    dest: /etc/sudoers.d/stack
    owner: root
    group: root
    mode: 0440
