---
- name: Check TripleO repo installed or not
  yum:
    list=python2-tripleo-repos
  register: pkg

- name: Install TripleO repo
  script: >
    files/get_tripleo_repo
  when: offline_install == false and pkg.results|selectattr("yumstate", "match", "installed")|list|length == 0
  tags: tripleo-rpm

- name: Enable TripleO repo "{{ tripleo_version }}"
  shell: tripleo-repos -b "{{ tripleo_version }}" current ceph
  become: true
  when: offline_install == false
  tags: tripleo-rpm

- name: Install tripleo client
  yum:
    name:
      - python-tripleoclient
  tags: install-pkgs

- name: Install ceph-ansible for external ceph
  yum:
    name:
      - ceph-ansible
  when: external_ceph == true
  tags: install-pkgs
